"""Ridgeline Engineering Partners document corpus for MP2 Part A."""

DOCUMENTS = [
    # ── CORPORATE ──────────────────────────────────────────────────────
    {
        "id": "DOC-001",
        "title": "Company Overview",
        "type": "corporate",
        "text": (
            "Ridgeline Engineering Partners is a mechanical engineering consultancy "
            "headquartered in Portland, Oregon. The firm was founded in 2007 by "
            "Dr. Catherine Marsh and David Okonkwo, both former senior engineers at "
            "Bechtel, who saw an opportunity to provide specialized structural and "
            "thermal analysis services to mid-market clients who could not justify "
            "full-time engineering staff for niche technical problems.\n\n"
            "Over the past eighteen years, the firm has grown from a two-person "
            "partnership to a consultancy employing 138 engineers and technical staff "
            "across three offices. Ridgeline's core competencies span structural "
            "analysis, thermal management, mechanical design, and prototype "
            "development. The firm serves clients in transportation infrastructure, "
            "consumer electronics, HVAC systems, and medical devices. Annual revenue "
            "for fiscal year 2024 was approximately $42 million, representing a 12% "
            "increase over the prior year.\n\n"
            "Ridgeline's mission statement, adopted in 2015, reads: 'We deliver "
            "rigorous engineering analysis that helps our clients build safer, more "
            "efficient, and more reliable products and infrastructure.' The firm "
            "holds ISO 9001:2015 certification and maintains professional liability "
            "insurance through Hartford Engineering Underwriters. Key long-term "
            "clients include Millbrook County Department of Transportation, Cascade "
            "Consumer Products, and NovaMed Devices.\n\n"
            "Dr. Marsh currently serves as Managing Partner and oversees the "
            "Portland and Denver offices. David Okonkwo leads the firm's business "
            "development efforts and manages the Seattle office. The firm's "
            "technical advisory board includes Dr. Patricia Nguyen (Stanford, "
            "computational mechanics), Dr. James Whitfield (Georgia Tech, thermal "
            "sciences), and Professor Rachel Kim (University of Washington, "
            "biomedical engineering)."
        ),
    },
    {
        "id": "DOC-002",
        "title": "Seattle Office Memo",
        "type": "corporate",
        "text": (
            "INTERNAL MEMO\n"
            "TO: All Staff\n"
            "FROM: David Okonkwo, Partner\n"
            "DATE: January 15, 2025\n"
            "RE: Seattle Office Update and Growth Plan\n\n"
            "I am pleased to share an update on our Seattle operations as we begin "
            "the new year. As many of you know, the Seattle office was established "
            "to better serve our growing client base in the Puget Sound region, "
            "particularly in the aerospace supply chain and medical device sectors.\n\n"
            "Our Seattle office opened in 2019 and has grown steadily since then. "
            "We currently employ 47 engineers at the Seattle location, spanning "
            "structural, thermal, and mechanical design disciplines. The office is "
            "located in the Fremont district at 3847 Leary Way NW, occupying the "
            "third and fourth floors of the Fremont Engineering Center. Our lease "
            "runs through December 2028 with an option to expand into the fifth "
            "floor.\n\n"
            "Key achievements for the Seattle office in 2024 include the completion "
            "of the CardioSense medical device enclosure project for NovaMed "
            "Devices, the Puget Sound Energy substation thermal assessment, and "
            "the initiation of three new aerospace supplier qualification projects. "
            "The office generated $14.2 million in revenue for FY 2024, exceeding "
            "our target by 8%.\n\n"
            "Looking ahead, we plan to add 10-12 engineers in 2025, with emphasis "
            "on hiring in finite element analysis and computational fluid dynamics. "
            "We are also evaluating a satellite workspace in Bellevue to accommodate "
            "staff who live on the Eastside. I encourage anyone interested in "
            "transferring to Seattle to reach out to HR. The cost-of-living "
            "adjustment for Seattle-based staff is 7% above the Portland baseline."
        ),
    },
    {
        "id": "DOC-003",
        "title": "Leadership and Organization Chart",
        "type": "corporate",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — ORGANIZATIONAL STRUCTURE\n"
            "Effective January 1, 2025\n\n"
            "EXECUTIVE LEADERSHIP\n"
            "Managing Partner: Dr. Catherine Marsh, PE, PhD (Portland)\n"
            "Partner, Business Development: David Okonkwo, PE (Seattle)\n"
            "Chief Financial Officer: Margaret Sullivan, CPA (Portland)\n"
            "Director of Engineering: Brian Tanaka, PE (Portland)\n"
            "Director of Quality: Lisa Fernandez, PE (Denver)\n\n"
            "PRACTICE GROUPS\n\n"
            "Structural Analysis Group — Led by Dr. Sarah Hendricks, PE, PhD\n"
            "  Headcount: 34 engineers across all offices\n"
            "  Focus: bridges, buildings, industrial structures, seismic assessment\n"
            "  Key standards: AASHTO LRFD, AISC 360, ACI 318, ASCE 7\n\n"
            "Thermal & Fluids Group — Led by Mark Jensen, PE\n"
            "  Headcount: 28 engineers\n"
            "  Focus: electronics cooling, HVAC optimization, heat exchanger design\n"
            "  Key tools: ANSYS Fluent, COMSOL Multiphysics, FloTHERM\n\n"
            "Mechanical Design Group — Led by Angela Cruz, PE\n"
            "  Headcount: 31 engineers\n"
            "  Focus: product design, mechanism design, tolerance analysis, DFM\n"
            "  Key tools: SolidWorks, Creo, GD&T per ASME Y14.5-2018\n\n"
            "Prototype & Testing Group — Led by Ryan Cho, PE\n"
            "  Headcount: 18 engineers and technicians\n"
            "  Focus: rapid prototyping, environmental testing, validation\n"
            "  Facilities: 4,200 sq ft test lab in Portland, 1,800 sq ft in Denver\n\n"
            "Project Management Office — Led by Karen Weatherby, PMP\n"
            "  Headcount: 12 project managers and coordinators\n"
            "  Tools: Microsoft Project, Jira, SharePoint\n\n"
            "OFFICE LOCATIONS\n"
            "Portland HQ: 2100 NW Flanders Street, Suite 400, Portland, OR 97210\n"
            "Seattle: 3847 Leary Way NW, 3rd/4th Floor, Seattle, WA 98107\n"
            "Denver: 1550 Wewatta Street, Suite 200, Denver, CO 80202\n\n"
            "Total firm headcount as of January 2025: 138 engineers and technical "
            "staff, plus 27 administrative and support personnel."
        ),
    },
    {
        "id": "DOC-004",
        "title": "Employee Handbook Excerpts — Training and Development",
        "type": "corporate",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — EMPLOYEE HANDBOOK (Rev. 8, 2024)\n"
            "CHAPTER 7: PROFESSIONAL DEVELOPMENT AND TRAINING\n\n"
            "7.1 Continuing Education Requirements\n"
            "Ridgeline is committed to the ongoing professional development of all "
            "engineering staff. To maintain technical excellence and meet "
            "professional licensing requirements, all engineers are required to "
            "complete a minimum of 24 hours of continuing education per year. At "
            "least 12 of these hours must be in technical topics directly related "
            "to the employee's practice area. The remaining 12 hours may include "
            "professional skills development, project management training, or "
            "approved industry conference attendance.\n\n"
            "7.2 Tuition Reimbursement\n"
            "Full-time employees with at least one year of service are eligible for "
            "tuition reimbursement up to $8,500 per calendar year for approved "
            "graduate coursework. Courses must be at an accredited institution and "
            "directly relevant to the employee's role. Employees must receive a "
            "grade of B or better to qualify for reimbursement. Applications are "
            "submitted through the HR portal and require manager approval.\n\n"
            "7.3 PE License Support\n"
            "Ridgeline strongly encourages all eligible engineers to pursue "
            "Professional Engineer licensure. The firm covers the cost of the PE "
            "exam (currently $375), provides up to 40 hours of paid study time, "
            "and offers a $2,500 bonus upon successful completion. Engineers who "
            "hold a PE license are eligible for accelerated promotion consideration.\n\n"
            "7.4 Conference Attendance\n"
            "Each practice group has an annual conference budget. Engineers may "
            "attend up to two approved conferences per year with full travel "
            "coverage. Priority is given to employees presenting papers or serving "
            "on technical committees. Approved conferences include ASME IMECE, "
            "AIAA SciTech, SAE WCX, IEEE ITHERM, and regional ASCE meetings.\n\n"
            "7.5 Internal Training\n"
            "Monthly 'Lunch & Learn' sessions are held at each office, covering "
            "technical topics, software tool updates, and project case studies. "
            "Attendance counts toward the 24-hour continuing education requirement. "
            "Senior engineers are expected to present at least once per year."
        ),
    },
    {
        "id": "DOC-005",
        "title": "Office Locations and Facilities",
        "type": "corporate",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — FACILITIES OVERVIEW\n\n"
            "PORTLAND HEADQUARTERS\n"
            "Address: 2100 NW Flanders Street, Suite 400, Portland, OR 97210\n"
            "Established: 2007 (founding location)\n"
            "Staff: 72 engineers, 18 administrative\n"
            "Square footage: 14,500 sq ft office space\n"
            "The Portland office houses the firm's leadership team, the largest "
            "concentration of structural engineers, and the primary prototype and "
            "testing laboratory. The 4,200 sq ft test lab includes a 50 kN "
            "universal testing machine (Instron 5985), a thermal cycling chamber "
            "(-70C to +180C), and a full suite of dimensional metrology equipment "
            "including a Zeiss Contura CMM. The office underwent a major renovation "
            "in 2021, adding a dedicated FEA computation room with a 128-core "
            "analysis cluster.\n\n"
            "SEATTLE OFFICE\n"
            "Address: 3847 Leary Way NW, 3rd/4th Floor, Seattle, WA 98107\n"
            "Established: 2019\n"
            "Staff: 47 engineers, 6 administrative\n"
            "Square footage: 8,200 sq ft office space\n"
            "The Seattle office focuses primarily on medical device engineering "
            "and aerospace supplier support. The office includes a small materials "
            "testing area with hardness testing and basic tensile testing capability. "
            "Proximity to the University of Washington enables active collaboration "
            "with faculty in the Mechanical Engineering and Bioengineering "
            "departments.\n\n"
            "DENVER OFFICE\n"
            "Address: 1550 Wewatta Street, Suite 200, Denver, CO 80202\n"
            "Established: 2016\n"
            "Staff: 19 engineers, 3 administrative\n"
            "Square footage: 4,100 sq ft office space\n"
            "The Denver office primarily serves energy sector clients in Colorado "
            "and Wyoming, specializing in thermal management for power generation "
            "equipment and renewable energy installations. The office includes a "
            "1,800 sq ft environmental testing lab with salt spray, UV exposure, "
            "and humidity cycling chambers. Director of Quality Lisa Fernandez "
            "is based in Denver and oversees the firm's ISO 9001 compliance program."
        ),
    },

    # ── TECHNICAL ──────────────────────────────────────────────────────
    {
        "id": "DOC-006",
        "title": "Project Summary — Millbrook County Bridge Assessment",
        "type": "technical",
        "text": (
            "PROJECT SUMMARY REPORT\n"
            "Project: Millbrook County DOT Bridge Load Rating Assessment\n"
            "Project Number: REP-2023-047\n"
            "Client: Millbrook County Department of Transportation\n"
            "Project Manager: Dr. Sarah Hendricks, PE, PhD\n"
            "Date Completed: August 2024\n"
            "Budget: $285,000 | Actual: $271,400\n\n"
            "SCOPE\n"
            "Ridgeline was engaged by the Millbrook County DOT to perform a "
            "comprehensive load rating assessment of the Cedar Creek Bridge (Bridge "
            "No. MC-4412), a three-span continuous steel plate girder bridge "
            "constructed in 1987. The bridge carries State Route 26 over Cedar Creek "
            "and has an average daily traffic count of 8,400 vehicles.\n\n"
            "METHODOLOGY\n"
            "The assessment was conducted in accordance with AASHTO LRFD 9th edition "
            "bridge design specifications and the AASHTO Manual for Bridge Evaluation "
            "(3rd edition). Field inspection included detailed measurement of all "
            "structural members, documentation of section loss due to corrosion, and "
            "concrete deck condition survey. A three-dimensional finite element model "
            "was constructed using CSiBridge software, calibrated against field "
            "measurements and a controlled load test using a 72,000 lb test vehicle.\n\n"
            "KEY FINDINGS\n"
            "The analysis identified the interior girders at the first span as the "
            "controlling members. The load rating analysis produced a rating factor "
            "of 0.73 for the interior girders under HL-93 loading, which is below "
            "the acceptable threshold of 1.0. This deficiency is primarily "
            "attributable to 15-18% section loss in the bottom flange at the "
            "pier locations due to pack rust between the girder flanges and the "
            "bearing stiffeners. Exterior girders rated satisfactorily at 1.12.\n\n"
            "RECOMMENDATIONS\n"
            "Immediate posting of the bridge for a 15-ton weight restriction is "
            "recommended. Ridgeline further recommends targeted steel repairs at "
            "the pier locations, estimated at $420,000, which would restore the "
            "rating factor above 1.0. A full deck replacement should be programmed "
            "within the next 8-10 years based on the deck condition survey results."
        ),
    },
    {
        "id": "DOC-007",
        "title": "Project Summary — Cascade Thermal Management Study",
        "type": "technical",
        "text": (
            "PROJECT SUMMARY REPORT\n"
            "Project: Cascade CP-2200 Portable Speaker Thermal Analysis\n"
            "Project Number: REP-2024-012\n"
            "Client: Cascade Consumer Products\n"
            "Project Manager: Mark Jensen, PE\n"
            "Date Completed: March 2024\n"
            "Budget: $95,000 | Actual: $89,200\n\n"
            "BACKGROUND\n"
            "Cascade Consumer Products retained Ridgeline to evaluate the thermal "
            "performance of their CP-2200 portable Bluetooth speaker, which had "
            "experienced field returns due to thermal shutdown during extended outdoor "
            "use in direct sunlight. The speaker uses a Class D amplifier rated at "
            "40W RMS that dissipates approximately 8W of heat at maximum output.\n\n"
            "ANALYSIS\n"
            "Ridgeline constructed a detailed thermal model using FloTHERM, "
            "incorporating the amplifier IC, battery pack (4-cell 18650 lithium-ion), "
            "PCB, enclosure, and passive radiator. Boundary conditions simulated "
            "worst-case outdoor use: 40C ambient temperature, 1000 W/m2 solar "
            "radiation on the top surface, and natural convection only (no wind).\n\n"
            "The analysis identified that the amplifier junction temperature reached "
            "118C under worst-case conditions, exceeding the 110C thermal shutdown "
            "threshold. The primary heat path from the amplifier IC to the enclosure "
            "surface was constrained by a 2mm air gap between the PCB and the "
            "enclosure wall. Battery temperatures reached 52C, which is within the "
            "safe operating range but reduces cycle life.\n\n"
            "SOLUTION\n"
            "Ridgeline recommended three design modifications: (1) adding a "
            "0.5mm-thick graphite thermal interface pad between the amplifier IC and "
            "the enclosure wall, reducing thermal resistance by 62%; (2) increasing "
            "the ventilation slot area on the bottom of the enclosure by 40%; and "
            "(3) applying a selective high-emissivity coating (emissivity 0.92) to "
            "the interior surfaces near the amplifier. With all three modifications, "
            "the predicted worst-case junction temperature dropped to 98C, providing "
            "a 12C margin below the shutdown threshold. Cascade implemented all "
            "three recommendations and eliminated the thermal shutdown returns."
        ),
    },
    {
        "id": "DOC-008",
        "title": "Project Summary — Greenfield Plaza HVAC Optimization",
        "type": "technical",
        "text": (
            "PROJECT SUMMARY REPORT\n"
            "Project: Greenfield Plaza HVAC System Optimization\n"
            "Project Number: REP-2023-089\n"
            "Client: Greenfield Properties LLC\n"
            "Project Manager: Mark Jensen, PE\n"
            "Date Completed: November 2023\n"
            "Budget: $175,000 | Actual: $168,300\n\n"
            "BACKGROUND\n"
            "Greenfield Properties engaged Ridgeline to optimize the HVAC system "
            "in the Greenfield Plaza, a 120,000 sq ft Class A office building in "
            "downtown Portland constructed in 2004. The building's original HVAC "
            "system — four Trane RTAC 200-ton air-cooled chillers and 24 variable "
            "air volume (VAV) air handling units — was consuming significantly more "
            "energy than comparable buildings, with an Energy Use Intensity (EUI) of "
            "142 kBtu/sq ft/yr compared to the ASHRAE 90.1-2019 baseline of 95 "
            "kBtu/sq ft/yr for the climate zone.\n\n"
            "ANALYSIS AND FINDINGS\n"
            "Ridgeline performed a comprehensive energy audit including sub-metering "
            "of major equipment, thermal imaging of the building envelope, and "
            "occupancy pattern analysis. Key findings included: (1) two of the four "
            "chillers were operating below 60% of rated efficiency due to refrigerant "
            "undercharge and fouled condenser coils; (2) the building automation "
            "system (BAS) scheduling had not been updated since 2012 and did not "
            "reflect current tenant occupancy patterns; (3) the economizer dampers "
            "on 8 of the 24 AHUs were stuck in the minimum position, eliminating "
            "free cooling capability during mild weather.\n\n"
            "RECOMMENDATIONS AND RESULTS\n"
            "Ridgeline implemented a phased optimization: Phase 1 addressed the "
            "chiller maintenance and economizer repairs (completed in 6 weeks). "
            "Phase 2 reprogrammed the BAS with updated schedules and optimal start "
            "algorithms. Phase 3 replaced the original constant-speed condenser fans "
            "with variable frequency drives. The combined effect reduced the "
            "building's EUI from 142 to 98 kBtu/sq ft/yr — a 31% reduction in "
            "energy consumption. Projected annual energy cost savings are $127,000, "
            "yielding a simple payback period of 1.3 years on the $168,300 project "
            "investment."
        ),
    },
    {
        "id": "DOC-009",
        "title": "Project Summary — CardioSense Medical Device Enclosure",
        "type": "technical",
        "text": (
            "PROJECT SUMMARY REPORT\n"
            "Project: CardioSense Wearable Monitor Enclosure Design\n"
            "Project Number: REP-2024-031\n"
            "Client: NovaMed Devices, Inc.\n"
            "Project Manager: Angela Cruz, PE\n"
            "Date Completed: June 2024\n"
            "Budget: $310,000 | Actual: $298,500\n\n"
            "BACKGROUND\n"
            "NovaMed Devices engaged Ridgeline to design the enclosure for the "
            "CardioSense CS-400, a next-generation wearable cardiac rhythm monitor "
            "intended for continuous 14-day patient wear. The device houses a "
            "custom ASIC, a 3-axis accelerometer, a rechargeable lithium polymer "
            "battery (450 mAh), and flexible electrode leads. The enclosure must "
            "protect sensitive electronics while being comfortable for extended "
            "skin contact.\n\n"
            "DESIGN REQUIREMENTS\n"
            "The primary design challenges centered on environmental protection and "
            "biocompatibility. The enclosure was required to achieve an IP67 rating "
            "(dust-tight and protected against temporary immersion in water up to 1m "
            "for 30 minutes), as patients must be able to shower while wearing the "
            "device. Additionally, all external surfaces required biocompatibility "
            "per ISO 10993 for prolonged skin contact. Maximum enclosure dimensions "
            "were constrained to 62mm x 42mm x 11mm, and total weight including "
            "electronics could not exceed 28 grams.\n\n"
            "MATERIAL SELECTION AND DESIGN\n"
            "After evaluating six candidate materials, Ridgeline selected glass-filled "
            "nylon PA66-GF30 for the enclosure body. This material provides the "
            "required mechanical strength (tensile strength 185 MPa), dimensional "
            "stability, and chemical resistance while meeting the weight target. The "
            "glass-filled nylon also offers excellent moldability for the thin-wall "
            "sections (minimum wall thickness 0.8mm) required by the size constraint. "
            "The sealing system uses a liquid silicone rubber (LSR) gasket in a "
            "precision-molded groove, achieving the IP67 rating with a safety margin "
            "validated to IP68 conditions (1.5m for 60 minutes). Surface finish is "
            "SPI-B2 (matte) to minimize skin irritation.\n\n"
            "VERIFICATION\n"
            "Twelve prototype units were manufactured via injection molding at a "
            "contract manufacturer in Shenzhen. Environmental testing confirmed IP67 "
            "compliance across all units. Drop testing from 1.5m onto concrete "
            "showed no cracking or seal failure. Biocompatibility testing per ISO "
            "10993-5 (cytotoxicity) and ISO 10993-10 (skin sensitization) passed "
            "with no adverse findings."
        ),
    },
    {
        "id": "DOC-010",
        "title": "Technical Standards Reference Guide",
        "type": "technical",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — TECHNICAL STANDARDS GUIDE\n"
            "Revision 12, Updated September 2024\n"
            "Maintained by: Lisa Fernandez, PE, Director of Quality\n\n"
            "This document lists the primary technical standards referenced across "
            "Ridgeline's practice areas. Engineers must use the editions listed below "
            "unless a client contract specifies otherwise. Copies of all listed "
            "standards are available in the firm's digital standards library "
            "(SharePoint > Technical Resources > Standards Library).\n\n"
            "STRUCTURAL ANALYSIS\n"
            "- AASHTO LRFD Bridge Design Specifications, 9th Edition (2020)\n"
            "- AASHTO Manual for Bridge Evaluation, 3rd Edition (2018)\n"
            "- AISC 360-22: Specification for Structural Steel Buildings\n"
            "- ACI 318-19: Building Code Requirements for Structural Concrete\n"
            "- ASCE 7-22: Minimum Design Loads for Buildings\n"
            "- AWS D1.1/D1.1M-2020: Structural Welding Code — Steel\n\n"
            "THERMAL AND FLUID ANALYSIS\n"
            "- ASHRAE Standard 90.1-2019: Energy Standard for Buildings\n"
            "- ASHRAE Handbook — Fundamentals (2021 edition)\n"
            "- IPC-2152: Standard for Determining Current-Carrying Capacity in PCBs\n"
            "- JEDEC JESD51-14: Transient Dual Interface Test Method\n\n"
            "MECHANICAL DESIGN\n"
            "- ASME Y14.5-2018: Dimensioning and Tolerancing\n"
            "- ASME Y14.100-2017: Engineering Drawing Practices\n"
            "- ISO 2768-1:1989: General Tolerances (linear and angular)\n"
            "- ISO 286-1:2010: ISO System of Limits and Fits\n\n"
            "MEDICAL DEVICES\n"
            "- ISO 13485:2016: Quality Management Systems for Medical Devices\n"
            "- ISO 14971:2019: Application of Risk Management to Medical Devices\n"
            "- IEC 60601-1: Medical Electrical Equipment — General Requirements\n"
            "- ISO 10993 series: Biological Evaluation of Medical Devices\n\n"
            "QUALITY AND TESTING\n"
            "- ISO 9001:2015: Quality Management Systems — Requirements\n"
            "- ASTM E8/E8M: Standard Test Methods for Tension Testing of Metals\n"
            "- ASTM D638: Standard Test Method for Tensile Properties of Plastics\n"
            "- IEC 60529: Degrees of Protection Provided by Enclosures (IP Code)\n\n"
            "Engineers are responsible for verifying that the applicable edition of "
            "any standard has not been superseded before beginning analysis. The "
            "Quality Director distributes quarterly updates on new standard editions."
        ),
    },
    {
        "id": "DOC-011",
        "title": "Material Selection Report — Automotive Suspension Bracket",
        "type": "technical",
        "text": (
            "MATERIAL SELECTION REPORT\n"
            "Project: Duraline Automotive Rear Suspension Bracket Redesign\n"
            "Project Number: REP-2024-055\n"
            "Author: Dr. Sarah Hendricks, PE, PhD\n"
            "Date: October 2024\n\n"
            "OBJECTIVE\n"
            "Select a replacement material for the Duraline RA-800 rear suspension "
            "bracket, currently manufactured from SAE 1045 hot-rolled steel. The "
            "client's objectives are a 25% weight reduction while maintaining "
            "equivalent fatigue life (minimum 500,000 cycles at peak load) and "
            "staying within a per-part cost increase of no more than 30%.\n\n"
            "CANDIDATE MATERIALS EVALUATED\n"
            "1. SAE 1045 Steel (baseline): Yield 530 MPa, density 7.85 g/cm3, "
            "cost index 1.0\n"
            "2. HSLA 350W Steel: Yield 350 MPa, density 7.85 g/cm3, cost index 1.05\n"
            "3. 6061-T6 Aluminum: Yield 276 MPa, density 2.71 g/cm3, cost index 2.8\n"
            "4. 7075-T6 Aluminum: Yield 503 MPa, density 2.81 g/cm3, cost index 4.1\n"
            "5. S-2 Glass/Epoxy Composite: Tensile 1,200 MPa, density 2.0 g/cm3, "
            "cost index 8.5\n\n"
            "ANALYSIS METHOD\n"
            "Ashby-style material indices were calculated for the stiffness-limited "
            "and strength-limited design cases. FEA was performed for each candidate "
            "using optimized cross-sections that exploit each material's properties. "
            "Fatigue analysis followed the stress-life approach per SAE J1099.\n\n"
            "RECOMMENDATION\n"
            "6061-T6 aluminum is recommended. While the raw yield strength is lower "
            "than the steel baseline, the 65% density reduction enables a redesigned "
            "cross-section that achieves equivalent stiffness at 38% lower weight. "
            "The thicker aluminum sections provide better fatigue performance in the "
            "bracket geometry (predicted life: 720,000 cycles vs. the 500,000 cycle "
            "requirement). The per-part cost increase is estimated at 22%, within "
            "the client's 30% budget. The 7075-T6 option offers higher strength but "
            "the 4.1x cost multiplier exceeds the budget, and the modest additional "
            "weight savings (3%) does not justify the premium. Composite options were "
            "eliminated due to cost and manufacturing complexity for the production "
            "volume (15,000 units/year)."
        ),
    },

    # ── BUSINESS ───────────────────────────────────────────────────────
    {
        "id": "DOC-012",
        "title": "Vendor Communication Policy",
        "type": "business",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — VENDOR COMMUNICATION POLICY\n"
            "Policy Number: ADM-2023-008\n"
            "Effective Date: March 1, 2023\n"
            "Last Reviewed: January 2025\n"
            "Policy Owner: Margaret Sullivan, CFO\n\n"
            "1. PURPOSE\n"
            "This policy establishes guidelines for all communications between "
            "Ridgeline staff and external vendors, subcontractors, and material "
            "suppliers. Proper vendor communication protects client confidentiality, "
            "ensures consistent pricing, and maintains professional standards.\n\n"
            "2. AUTHORIZED VENDOR CONTACTS\n"
            "Only Project Managers, Practice Group Leads, and Partners are authorized "
            "to negotiate pricing, delivery terms, or contract modifications with "
            "vendors. Engineers may communicate directly with vendors for technical "
            "information exchange (e.g., material data sheets, software support) but "
            "must not discuss pricing, project budgets, or client identities without "
            "PM approval.\n\n"
            "3. APPROVED VENDOR LIST\n"
            "Ridgeline maintains an Approved Vendor List (AVL) reviewed annually by "
            "the Director of Quality. As of January 2025, the AVL includes 84 "
            "approved vendors across categories including materials testing "
            "laboratories, prototype fabrication shops, software licensors, and "
            "calibration services. New vendors must complete the Vendor Qualification "
            "Questionnaire (Form QA-VQ-01) and pass an initial assessment before "
            "being added to the AVL.\n\n"
            "4. CONFIDENTIALITY\n"
            "All vendor communications must comply with the firm's NDA obligations. "
            "Client names, project details, and proprietary design information must "
            "not be shared with vendors unless a project-specific NDA is in place. "
            "Technical drawings shared with fabrication vendors must be marked "
            "'CONFIDENTIAL — RIDGELINE ENGINEERING PARTNERS' and include the "
            "appropriate distribution restriction code.\n\n"
            "5. PAYMENT TERMS\n"
            "Standard payment terms for vendor invoices are Net 30. Exceptions "
            "require CFO approval. Vendors offering early payment discounts (e.g., "
            "2/10 Net 30) should be flagged for review by Accounts Payable."
        ),
    },
    {
        "id": "DOC-013",
        "title": "Proposal Development Guidelines",
        "type": "business",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — PROPOSAL DEVELOPMENT GUIDE\n"
            "Revision 5, Updated August 2024\n"
            "Maintained by: David Okonkwo, Partner\n\n"
            "This guide provides the standard framework for developing client "
            "proposals. All proposals must follow this format unless the client's "
            "RFP specifies a different structure.\n\n"
            "PROPOSAL STRUCTURE\n\n"
            "Section 1: Executive Summary (1 page max)\n"
            "Concise statement of the client's problem, Ridgeline's proposed "
            "approach, and the key benefit to the client. Written last but placed "
            "first. Avoid technical jargon.\n\n"
            "Section 2: Understanding of the Problem (1-2 pages)\n"
            "Demonstrate that Ridgeline understands the client's situation, "
            "constraints, and objectives. Reference any prior work with the client. "
            "Identify the key engineering questions that must be answered.\n\n"
            "Section 3: Technical Approach (2-4 pages)\n"
            "Detailed description of the proposed methodology, analysis tools, and "
            "deliverables. Include the standards and codes that will govern the work. "
            "Identify assumptions and limitations. If applicable, reference similar "
            "projects Ridgeline has completed.\n\n"
            "Section 4: Project Team (1 page)\n"
            "Brief bios of the proposed Project Manager and key technical staff. "
            "Include relevant PE licenses, advanced degrees, and directly relevant "
            "project experience.\n\n"
            "Section 5: Schedule and Milestones (1 page)\n"
            "Gantt chart or milestone table showing major deliverables and review "
            "points. Include a kickoff meeting within the first week and interim "
            "progress reviews at minimum 30-day intervals.\n\n"
            "Section 6: Fee Proposal (1 page)\n"
            "Presented as time-and-materials with a not-to-exceed cap, unless the "
            "client requests fixed-price. Reference the current billing rate schedule "
            "(see DOC-014). Include estimated hours by role and a 10% contingency "
            "line item for unforeseen scope. All proposals over $100,000 require "
            "Partner review before submission.\n\n"
            "APPROVAL REQUIREMENTS\n"
            "Proposals under $50,000: PM approval\n"
            "Proposals $50,000 - $100,000: Practice Group Lead approval\n"
            "Proposals over $100,000: Partner approval\n\n"
            "Average proposal win rate for FY 2024: 34% (42 wins out of 124 "
            "proposals submitted). Target for FY 2025: 38%."
        ),
    },
    {
        "id": "DOC-014",
        "title": "Standard Billing Rate Schedule — FY 2025",
        "type": "business",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS\n"
            "STANDARD BILLING RATE SCHEDULE\n"
            "Effective: January 1, 2025\n"
            "Approved by: Dr. Catherine Marsh, Managing Partner\n\n"
            "The following rates apply to all time-and-materials engagements unless "
            "a project-specific rate agreement has been negotiated and approved by "
            "a Partner. Rates are reviewed annually and adjusted based on market "
            "conditions, cost of living, and competitive positioning.\n\n"
            "ENGINEERING STAFF\n"
            "Principal Engineer / Partner ............ $295/hour\n"
            "Associate Principal Engineer ............ $250/hour\n"
            "Senior Engineer III ..................... $215/hour\n"
            "Senior Engineer II ...................... $185/hour\n"
            "Senior Engineer I ....................... $165/hour\n"
            "Engineer III ............................ $145/hour\n"
            "Engineer II ............................. $130/hour\n"
            "Engineer I .............................. $115/hour\n"
            "Engineering Technician .................. $85/hour\n\n"
            "PROJECT MANAGEMENT\n"
            "Senior Project Manager .................. $195/hour\n"
            "Project Manager ......................... $165/hour\n"
            "Project Coordinator ..................... $105/hour\n\n"
            "SPECIALTY SERVICES\n"
            "Expert Witness Testimony ................ $450/hour\n"
            "Expert Witness Preparation .............. $350/hour\n"
            "Deposition Attendance ................... $400/hour\n"
            "Field Inspection (includes travel) ...... Rate + $75/hour premium\n\n"
            "EXPENSES\n"
            "Travel: Billed at cost (coach airfare, standard hotel, GSA per diem)\n"
            "Mileage: IRS standard rate ($0.67/mile for 2025)\n"
            "Printing and reproduction: Billed at cost\n"
            "Specialized software licenses: Billed at cost with 10% markup\n"
            "Subcontractor services: Billed at cost with 15% markup\n\n"
            "VOLUME DISCOUNTS\n"
            "Engagements exceeding $500,000 annually are eligible for a negotiated "
            "rate reduction of up to 10%. Discounted rates require Partner approval "
            "and must be documented in the project agreement.\n\n"
            "These rates represent a 4% increase over the FY 2024 schedule, "
            "reflecting market adjustments and the firm's investment in advanced "
            "analysis capabilities."
        ),
    },
    {
        "id": "DOC-015",
        "title": "Client Satisfaction Survey Results — 2024",
        "type": "business",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS\n"
            "CLIENT SATISFACTION SURVEY — 2024 ANNUAL RESULTS\n"
            "Prepared by: Karen Weatherby, PMP, Director of Project Management\n"
            "Date: December 2024\n\n"
            "METHODOLOGY\n"
            "The annual client satisfaction survey was distributed to project "
            "contacts for all engagements completed between January and October "
            "2024. Of 87 survey invitations sent, 54 responses were received "
            "(62% response rate, up from 58% in 2023). The survey uses a 1-5 "
            "Likert scale across six dimensions.\n\n"
            "RESULTS SUMMARY\n\n"
            "Category                        | 2024 Score | 2023 Score | Change\n"
            "Technical Quality               |    4.6     |    4.5     |  +0.1\n"
            "Communication & Responsiveness  |    4.3     |    4.1     |  +0.2\n"
            "Schedule Adherence              |    4.1     |    3.9     |  +0.2\n"
            "Budget Management               |    4.2     |    4.2     |   0.0\n"
            "Value for Fee                   |    4.0     |    3.8     |  +0.2\n"
            "Overall Satisfaction            |    4.4     |    4.2     |  +0.2\n\n"
            "Overall satisfaction improved from 4.2 to 4.4 on the 5-point scale. "
            "The largest improvements were in Communication & Responsiveness and "
            "Value for Fee, both reflecting the firm's investment in project "
            "management training during 2024.\n\n"
            "KEY THEMES FROM OPEN-ENDED RESPONSES\n"
            "Positive: Clients consistently praised the depth of technical expertise, "
            "particularly in structural and thermal analysis. Several clients "
            "specifically mentioned the quality of deliverable reports. Three clients "
            "cited Ridgeline's ability to meet aggressive schedules as a "
            "differentiator.\n\n"
            "Areas for improvement: The most common suggestion (12 of 54 responses) "
            "was improving the availability of interim progress updates, particularly "
            "for longer engagements. Five respondents requested more flexible billing "
            "arrangements, such as monthly fixed-fee retainers instead of hourly "
            "billing.\n\n"
            "NET PROMOTER SCORE\n"
            "NPS for 2024: +47 (up from +38 in 2023). 31 promoters, 19 passives, "
            "4 detractors. Industry benchmark for engineering consultancies is +32."
        ),
    },

    # ── ENGINEERING PROCESSES ──────────────────────────────────────────
    {
        "id": "DOC-016",
        "title": "Design Review Checklist",
        "type": "process",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — DESIGN REVIEW CHECKLIST\n"
            "Form Number: ENG-DR-01, Revision 7\n"
            "Effective Date: June 2024\n"
            "Maintained by: Brian Tanaka, PE, Director of Engineering\n\n"
            "This checklist is required for all design deliverables before client "
            "submission. The reviewing engineer must be a Senior Engineer I or above "
            "and must not have been involved in the original design work.\n\n"
            "GENERAL REQUIREMENTS\n"
            "[ ] Project number and title correctly identified on all deliverables\n"
            "[ ] Client name and contact verified\n"
            "[ ] Applicable codes and standards identified and correct edition used\n"
            "[ ] Design basis document reviewed and requirements traced\n"
            "[ ] All assumptions documented and justified\n"
            "[ ] Units consistent throughout (SI or US Customary, not mixed)\n\n"
            "ANALYSIS VERIFICATION\n"
            "[ ] Input data verified against source documents\n"
            "[ ] Boundary conditions reviewed for appropriateness\n"
            "[ ] Material properties sourced from approved references\n"
            "[ ] Load combinations per applicable code\n"
            "[ ] Independent hand calculation performed for critical results\n"
            "[ ] FEA mesh convergence study documented (if applicable)\n"
            "[ ] Results checked for physical reasonableness\n"
            "[ ] Safety factors or rating factors reported and assessed\n\n"
            "DRAWINGS AND MODELS\n"
            "[ ] GD&T per ASME Y14.5-2018\n"
            "[ ] Tolerances achievable by specified manufacturing process\n"
            "[ ] Material specifications called out correctly\n"
            "[ ] Surface finish requirements specified where needed\n"
            "[ ] All views necessary for fabrication included\n"
            "[ ] CAD model matches drawings (no undocumented changes)\n\n"
            "REPORT QUALITY\n"
            "[ ] Executive summary present and accurate\n"
            "[ ] Methodology clearly described\n"
            "[ ] All figures and tables numbered and captioned\n"
            "[ ] References complete and properly cited\n"
            "[ ] Conclusions supported by analysis results\n"
            "[ ] Recommendations actionable and prioritized\n"
            "[ ] Spell check and grammar review completed\n\n"
            "SIGN-OFF\n"
            "Reviewing Engineer: _____________ Date: _______\n"
            "Project Manager: _______________ Date: _______\n"
            "Any 'fail' item must be resolved and re-reviewed before submission."
        ),
    },
    {
        "id": "DOC-017",
        "title": "FEA Best Practices Guide",
        "type": "process",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — FEA BEST PRACTICES GUIDE\n"
            "Document Number: ENG-FEA-BP-01, Revision 4\n"
            "Effective Date: April 2024\n"
            "Author: Dr. Sarah Hendricks, PE, PhD\n"
            "Approved by: Brian Tanaka, PE, Director of Engineering\n\n"
            "This guide establishes minimum requirements for finite element analysis "
            "performed at Ridgeline. All FEA work must comply with these practices "
            "regardless of software platform (ANSYS, Abaqus, NASTRAN, CSiBridge, "
            "COMSOL, etc.).\n\n"
            "1. MODEL PLANNING\n"
            "Before constructing any FEA model, the analyst must prepare a brief "
            "analysis plan documenting: (a) the specific engineering questions the "
            "model must answer, (b) the expected failure modes or design-limiting "
            "conditions, (c) the level of modeling fidelity required (1D beam, 2D "
            "shell, 3D solid, or mixed), and (d) the acceptance criteria or code "
            "requirements that will be checked.\n\n"
            "2. MESH QUALITY AND CONVERGENCE\n"
            "All FEA models must include a mesh convergence study with a minimum of "
            "three refinement levels. The analyst must demonstrate that the key "
            "result (stress, displacement, temperature, etc.) changes by less than "
            "5% between the second and third refinement levels. Results from the "
            "converged mesh are reported. If convergence is not achieved in three "
            "levels, additional refinement is required. The mesh convergence study "
            "must be documented in the analysis report, including a table or plot "
            "showing the key result vs. mesh density for each refinement level.\n\n"
            "Element quality metrics must meet the following minimums:\n"
            "- Aspect ratio: < 5:1 for regions of interest, < 10:1 elsewhere\n"
            "- Jacobian ratio: > 0.5 for all elements\n"
            "- Warpage: < 15 degrees for shell elements\n"
            "- Skewness: < 0.8 for tetrahedral elements\n\n"
            "3. BOUNDARY CONDITIONS\n"
            "All boundary conditions must be justified in the analysis report. "
            "Symmetric and antisymmetric boundary conditions should be used where "
            "applicable to reduce model size. Support conditions must reflect actual "
            "hardware (e.g., bolted connections modeled with contact, not fixed "
            "nodes). Applied loads must be traceable to the design basis.\n\n"
            "4. MATERIAL PROPERTIES\n"
            "Material properties must be sourced from approved references (see DOC-010 "
            "Technical Standards Guide). For temperature-dependent analyses, "
            "properties must be specified at the appropriate temperature. Nonlinear "
            "material models (plasticity, creep, hyperelasticity) require documented "
            "test data or published curves with cited sources.\n\n"
            "5. RESULTS INTERPRETATION\n"
            "Stress results at singularities (sharp corners, point loads, constraints) "
            "must not be reported as design values. Stress linearization per ASME "
            "BPVC Section VIII Division 2 is required for pressure vessel analyses. "
            "All FEA results must be sanity-checked against hand calculations or "
            "known closed-form solutions where available.\n\n"
            "6. DOCUMENTATION\n"
            "Every FEA analysis must produce a summary sheet including: software and "
            "version, element types used, total node/element count, mesh convergence "
            "table, boundary condition summary, and key results with plots."
        ),
    },
    {
        "id": "DOC-018",
        "title": "Tolerance Analysis Procedure",
        "type": "process",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — TOLERANCE ANALYSIS PROCEDURE\n"
            "Document Number: ENG-TOL-01, Revision 3\n"
            "Effective Date: February 2024\n"
            "Author: Angela Cruz, PE, Mechanical Design Group Lead\n\n"
            "This procedure defines Ridgeline's standard approach for performing "
            "dimensional tolerance analysis on mechanical assemblies.\n\n"
            "1. SCOPE\n"
            "This procedure applies to all mechanical design projects where "
            "dimensional variation affects form, fit, or function. Tolerance "
            "analysis is mandatory for: (a) assemblies with more than 5 "
            "contributing dimensions, (b) assemblies with clearance or interference "
            "fits, (c) medical device components subject to design controls, and "
            "(d) any assembly where the client specifies a Cpk requirement.\n\n"
            "2. ANALYSIS METHODS\n\n"
            "2.1 Worst-Case Analysis\n"
            "Sum of all tolerances at their extreme limits. Guarantees 100% "
            "interchangeability but results in overly tight individual tolerances. "
            "Required for safety-critical assemblies and when production volumes "
            "are below 500 units.\n\n"
            "2.2 RSS (Root Sum of Squares) Analysis\n"
            "Statistical method assuming normally distributed, independent "
            "dimensional variations. Provides approximately 99.73% (3-sigma) "
            "assembly yield when all inputs are centered at nominal. Appropriate "
            "for production volumes above 500 units.\n\n"
            "2.3 Monte Carlo Simulation\n"
            "Numerical simulation using 10,000+ random samples drawn from actual "
            "or assumed distributions. Required for non-normal distributions, "
            "assemblies with more than 8 contributing dimensions, and cases where "
            "Cpk targets must be predicted. Ridgeline uses Crystal Ball or custom "
            "Python scripts for Monte Carlo analysis.\n\n"
            "3. REQUIRED OUTPUTS\n"
            "All tolerance analyses must produce:\n"
            "- Dimension chain diagram (1D or 2D as appropriate)\n"
            "- Nominal gap/interference calculation\n"
            "- Worst-case min/max assembly dimensions\n"
            "- Statistical assembly distribution (if RSS or Monte Carlo used)\n"
            "- Predicted yield or Cpk at the assembly level\n"
            "- Sensitivity ranking: which individual tolerances contribute most\n\n"
            "4. GD&T COMPLIANCE\n"
            "All tolerances referenced in the analysis must conform to ASME "
            "Y14.5-2018. Geometric tolerances (flatness, parallelism, position, "
            "etc.) must be converted to equivalent bilateral linear tolerances for "
            "the stack-up calculation using the methods described in the ASME Y14.5 "
            "standard and Bryan Fischer's 'Mechanical Tolerance Stackup and "
            "Analysis' (2nd edition, CRC Press, 2011)."
        ),
    },
    {
        "id": "DOC-019",
        "title": "Prototype Testing Protocol",
        "type": "process",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — PROTOTYPE TESTING PROTOCOL\n"
            "Document Number: ENG-PT-01, Revision 5\n"
            "Effective Date: May 2024\n"
            "Author: Ryan Cho, PE, Prototype & Testing Group Lead\n\n"
            "This protocol establishes minimum requirements for prototype testing "
            "performed in Ridgeline's test laboratories.\n\n"
            "1. GENERAL REQUIREMENTS\n\n"
            "1.1 Sample Size\n"
            "All prototype tests must use a minimum of 3 units to establish "
            "statistical validity. For tests intended to demonstrate reliability "
            "or fatigue life, a minimum of 5 units is required. For tests where "
            "manufacturing variation is a key concern (e.g., seal performance, "
            "snap-fit retention force), a minimum of 10 units is recommended. "
            "Sample size justification must be documented in the test plan.\n\n"
            "1.2 Test Plan Approval\n"
            "All prototype tests require a written test plan approved by the "
            "Project Manager and at least one Senior Engineer. The test plan must "
            "define: test objectives, pass/fail criteria, sample size, test "
            "procedure, equipment to be used, data to be collected, and the format "
            "of the test report.\n\n"
            "1.3 Equipment Calibration\n"
            "All measurement equipment used in prototype testing must have current "
            "calibration certificates. Calibration intervals follow manufacturer "
            "recommendations or 12 months, whichever is shorter. The Instron 5985 "
            "universal testing machine is calibrated semi-annually by Instron's "
            "field service team.\n\n"
            "2. TEST TYPES\n\n"
            "2.1 Mechanical Testing\n"
            "Tensile, compression, and bend testing per ASTM standards. Load cell "
            "capacity: 50 kN (Instron 5985) or 5 kN (Instron 3345 for smaller "
            "specimens). Strain measurement via extensometer or digital image "
            "correlation (DIC) system.\n\n"
            "2.2 Environmental Testing\n"
            "Thermal cycling: -40C to +85C, ramp rate 5C/min, hold 30 min at "
            "extremes. Humidity: 85C/85% RH for up to 1000 hours. Salt spray: "
            "per ASTM B117, neutral salt spray at 35C. UV exposure: per ASTM G154, "
            "cycle 4 with UVA-340 lamps.\n\n"
            "2.3 IP Rating Verification\n"
            "Ingress protection testing per IEC 60529. The Portland lab is equipped "
            "for testing up to IP67 (dust-tight, temporary immersion 1m/30min). "
            "IP68 and above requires outsourcing to NTS or Intertek.\n\n"
            "3. DATA MANAGEMENT\n"
            "All test data is stored on the firm's SharePoint server under "
            "Projects > [Project Number] > Testing. Raw data files, photographs, "
            "and videos are retained for a minimum of 7 years. Test reports must "
            "be reviewed by a Senior Engineer before release to the client."
        ),
    },
    {
        "id": "DOC-020",
        "title": "Quality Assurance Program Overview",
        "type": "process",
        "text": (
            "RIDGELINE ENGINEERING PARTNERS — QUALITY ASSURANCE PROGRAM\n"
            "Document Number: QA-PGM-01, Revision 6\n"
            "Effective Date: January 2025\n"
            "Quality Director: Lisa Fernandez, PE\n\n"
            "1. QUALITY POLICY\n"
            "Ridgeline Engineering Partners is committed to delivering engineering "
            "services that meet or exceed client requirements, comply with applicable "
            "codes and standards, and reflect current best practices in analysis and "
            "design. Quality is the responsibility of every employee.\n\n"
            "2. QUALITY MANAGEMENT SYSTEM\n"
            "The firm's QMS is certified to ISO 9001:2015 by Bureau Veritas. The "
            "certification was originally obtained in 2014 and has been maintained "
            "continuously through annual surveillance audits. The most recent "
            "recertification audit was completed in September 2024 with zero "
            "nonconformities.\n\n"
            "3. KEY QMS PROCESSES\n\n"
            "3.1 Design Control\n"
            "All design work follows a controlled process: design input review → "
            "analysis/design → independent technical review (per DOC-016) → client "
            "review → final deliverable. Changes to approved designs require a "
            "formal Design Change Notice (DCN) approved by the PM and reviewing "
            "engineer.\n\n"
            "3.2 Document Control\n"
            "All controlled documents are managed through the firm's SharePoint-based "
            "document control system. Documents are numbered, revisioned, and require "
            "approval before release. Superseded documents are archived but accessible "
            "for reference. The document register currently contains 847 controlled "
            "documents.\n\n"
            "3.3 Internal Audits\n"
            "Internal audits are conducted quarterly by trained internal auditors. "
            "Each practice group is audited at least once per year. Audit findings "
            "are tracked in the Corrective Action database. In 2024, 14 internal "
            "audit findings were recorded; 12 have been closed and 2 are in progress.\n\n"
            "3.4 Corrective and Preventive Action (CAPA)\n"
            "Nonconformities, client complaints, and audit findings trigger the CAPA "
            "process. Root cause analysis using the 5-Why method is required for all "
            "CAPAs. In 2024, 8 CAPAs were initiated, with an average closure time "
            "of 34 days.\n\n"
            "3.5 Management Review\n"
            "Senior leadership conducts a formal management review of the QMS "
            "semi-annually (June and December). Review inputs include audit results, "
            "client feedback (per DOC-015), CAPA status, resource needs, and "
            "improvement opportunities. Minutes are retained as controlled records."
        ),
    },
]
